package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/maaxton/waiveo-next/internal/shared/ulid"
)

// This file canonicalizes row identifiers a build that predates DAT-005a
// enforcement left behind.
//
// Why it has to exist: every write validates the RESULTING full row-set
// (validateAfterWrite), not just the row being written. Once DAT-005a is
// enforced, a single stored row whose id is not a canonical ULID makes the whole
// store WRITE-DEAD — readable, and every subsequent create/update/delete fails
// with ROW_ID_INVALID for a row the caller never touched. A store seeded by an
// older build is exactly that, so it cannot be unstuck by authoring alone; the
// illegal ids have to be rewritten out from under the validator.
//
// Why it rewrites rather than reseeds: the same store holds authored content. A
// deployed box's playlists, schedules and automations are the user's, and a
// scope node seeded on day one is the node their authored rows hang off. Wiping
// and reseeding would destroy authored data to fix a syntax rule, which the
// platform's never-wipe discipline forbids outright. So the migration preserves
// every row and every field, and only replaces the identifier text.
//
// The replacement is a FOLD, not a fresh mint (foldToCanonicalULID): the
// characters Crockford base32 excludes are mapped onto the symbols they were
// excluded in favour of. That gives three properties a fresh ulid.New could not:
// the new id is derived from the old one, so an operator reading a log or a
// backup can still correlate them; the mapping is deterministic, so the same
// store migrates to the same ids on every run and on every box; and a store
// seeded by the older build converges on exactly the ids a freshly seeded store
// carries today (SeedDemo's constants were regenerated by this same
// substitution), so a migrated box and a fresh box are not two divergent
// worlds.
//
// The fold has one property the rest of the file leans on: its OUTPUT is always
// a canonical ULID, and only a NON-canonical id is ever an input. So no rewrite
// target can also be a rewrite source — the mapping never chains. That is what
// makes a single unordered replacement pass correct, and what makes the whole
// migration idempotent: run it on its own output and there is nothing left to
// match.

// crockfordFold maps each character canonical Crockford base32 excludes onto the
// symbol it was excluded in favour of. I, L and O are Crockford's own documented
// decoding aliases (they decode as 1, 1 and 0). U is not an alias in the spec —
// Crockford drops it outright — so mapping it to V is this repository's
// convention, the same substitution the seed identifiers were regenerated with,
// and V is the symbol that takes U's place in the alphabet.
var crockfordFold = map[byte]byte{
	'I': '1',
	'L': '1',
	'O': '0',
	'U': 'V',
}

// foldToCanonicalULID rewrites id into a canonical ULID by upper-casing it
// (Crockford decoding is case-insensitive) and substituting the excluded
// characters. ok is false when the result still is not canonical — a wrong
// length, a character outside the alphabet and outside crockfordFold, or a
// leading symbol above 7 (which would overflow the 48-bit timestamp field). A
// fold is only ever attempted, and only ever needed, for an id ulid.Valid
// already rejected.
func foldToCanonicalULID(id string) (string, bool) {
	out := []byte(strings.ToUpper(id))
	for i, c := range out {
		if sub, ok := crockfordFold[c]; ok {
			out[i] = sub
		}
	}
	folded := string(out)
	if !ulid.Valid(folded) {
		return "", false
	}
	return folded, true
}

// IDRewrite is one identifier the migration replaced (or, from
// PlanRowIDMigration, would replace). Kind names the table the identifier
// addresses — which for a dangling scope-node parent_id is still scope_nodes,
// even though no such row is stored. This store can no longer ACCEPT a write
// that leaves a parent_id unresolved (validateAfterWrite's strict tree), but a
// store an older build wrote may already hold one on disk, and that is exactly
// the population this migration exists for: it has to be able to address a
// reference it would refuse to create.
type IDRewrite struct {
	Kind Kind
	From string
	To   string
}

// IDMigration reports the identifiers a run rewrote. A zero-length Rewrites
// means the store already conformed and nothing was written.
type IDMigration struct {
	Rewrites []IDRewrite
}

// BlockedID names one identifier the migration refused to rewrite, and why.
type BlockedID struct {
	Kind   Kind
	ID     string
	Reason string
}

// IDMigrationBlockedError is returned when at least one identifier cannot be
// folded, or would fold onto an id its table already holds. The migration is
// all-or-nothing: on this error NOTHING was written and the store is exactly as
// it was. It is deliberately not a partial success — an id this fold cannot
// derive a canonical ULID from did not come from SeedDemo or from any api/1
// write (the api layer mints every id server-side), so it is evidence of
// something unaccounted for, and inventing an unrelated identifier for it would
// silently sever whatever authored it from its own data.
type IDMigrationBlockedError struct {
	Blocked []BlockedID
}

func (e *IDMigrationBlockedError) Error() string {
	parts := make([]string, 0, len(e.Blocked))
	for _, b := range e.Blocked {
		parts = append(parts, fmt.Sprintf("%s id %q: %s", b.Kind, b.ID, b.Reason))
	}
	return "store: cannot canonicalize row ids (DAT-005a): " + strings.Join(parts, "; ")
}

// planIDRewrites reads every stored identifier and works out which ones violate
// DAT-005a and what each would become. It writes nothing, and is the single
// source of the plan for both the read-only report and the migrating write — so
// what an operator is shown is computed by the same code that later acts.
//
// It covers two populations. The first is every row's own id across every
// resource table (for preset_batches the id column holds the body's preset_id,
// DAT-005's byte-exact exception, so it is reached the same way). The second is
// scope-node parent_id values, which are the ONLY reference the data model lets
// dangle: an absent parent is a subtree boundary, so a parent_id need not appear
// as a stored row id and would otherwise be missed. Every other reference is
// required by ValidateRows to resolve to a present row, so its value is already
// in the first population.
//
// A non-canonical parent_id is worth rewriting even though DAT-005a does not
// govern reference fields: once the rule is enforced, no row can ever again be
// created with a non-canonical id, so such a reference is permanently
// unresolvable. Its folded form is the only value that could ever name a real
// node.
func planIDRewrites(ctx context.Context, q queryer) ([]IDRewrite, []BlockedID, error) {
	var plan []IDRewrite
	var blocked []BlockedID
	mapped := make(map[string]string)

	for _, kind := range allKinds {
		ids, err := readIDs(ctx, q, string(kind))
		if err != nil {
			return nil, nil, err
		}
		// Every id the table already holds, plus every id a rewrite in this
		// table is about to claim: a fold landing on either would collide on
		// the primary key, and picking a winner would silently merge two rows.
		claimed := make(map[string]bool, len(ids))
		for _, id := range ids {
			claimed[id] = true
		}
		for _, id := range ids {
			if ulid.Valid(id) {
				continue
			}
			folded, ok := foldToCanonicalULID(id)
			if !ok {
				blocked = append(blocked, BlockedID{Kind: kind, ID: id, Reason: "cannot be folded into a canonical ULID"})
				continue
			}
			if claimed[folded] {
				blocked = append(blocked, BlockedID{Kind: kind, ID: id, Reason: fmt.Sprintf("would fold onto %q, which %s already holds", folded, kind)})
				continue
			}
			claimed[folded] = true
			mapped[id] = folded
			plan = append(plan, IDRewrite{Kind: kind, From: id, To: folded})
		}
	}

	// Dangling scope-node parents. A parent that IS a stored row is already in
	// the plan above under the same From, and the fold is deterministic, so the
	// two agree by construction; only an unseen value adds an entry.
	nodes, err := readScopeNodes(ctx, q)
	if err != nil {
		return nil, nil, err
	}
	for _, n := range nodes {
		if n.ParentID == nil || ulid.Valid(*n.ParentID) {
			continue
		}
		if _, done := mapped[*n.ParentID]; done {
			continue
		}
		folded, ok := foldToCanonicalULID(*n.ParentID)
		if !ok {
			blocked = append(blocked, BlockedID{Kind: KindScopeNode, ID: *n.ParentID, Reason: "referenced as a parent_id and cannot be folded into a canonical ULID"})
			continue
		}
		mapped[*n.ParentID] = folded
		plan = append(plan, IDRewrite{Kind: KindScopeNode, From: *n.ParentID, To: folded})
	}

	sort.Slice(plan, func(i, j int) bool {
		if plan[i].Kind != plan[j].Kind {
			return plan[i].Kind < plan[j].Kind
		}
		return plan[i].From < plan[j].From
	})
	sort.Slice(blocked, func(i, j int) bool {
		if blocked[i].Kind != blocked[j].Kind {
			return blocked[i].Kind < blocked[j].Kind
		}
		return blocked[i].ID < blocked[j].ID
	})
	return plan, blocked, nil
}

// rewriteMapping flattens a plan into the old→new lookup the replacement pass
// applies. Distinct tables can legitimately share a From (the same folded value
// then names a row in each), which is why the plan is keyed by table but the
// mapping is not.
func rewriteMapping(plan []IDRewrite) map[string]string {
	m := make(map[string]string, len(plan))
	for _, rw := range plan {
		m[rw.From] = rw.To
	}
	return m
}

// rewriteIDsInJSON replaces every complete JSON string value that equals a
// rewritten identifier. Matching on the quoted token is what makes this precise
// rather than a blind search-and-replace: the closing quote anchors the match,
// so a rewritten id can never be substituted into the middle of a longer string.
//
// It is deliberately key-agnostic. Reference identifiers appear under a dozen
// different keys (scope_node, parent_id, schedule_id, playlist_id,
// preset_batch_id, fallback_id, an automation action's preset_id) and at
// arbitrary depth inside a rule body's nested and/or/not conditions and branch
// actions. Enumerating those keys would make the migration silently wrong the
// day a new one is added; matching the VALUE cannot miss one. Nothing is at risk
// from over-reach, because the only values it looks for are identifiers that
// were unusable by definition.
//
// The one place an identifier can hide from this is inside a longer string — a
// rules/1 expression literal such as state('…'). Those hold device-plane entity
// ids, which live in a different, in-memory id space and are never rewritten
// here, so no such value is ever in the mapping.
//
// Replacement order does not matter: no To is ever a From (see the file header),
// so the passes cannot chain.
func rewriteIDsInJSON(body string, mapping map[string]string) string {
	for from, to := range mapping {
		body = strings.ReplaceAll(body, `"`+from+`"`, `"`+to+`"`)
	}
	return body
}

// remap returns the rewritten form of an identifier, or the identifier
// unchanged when it is not one the plan touches.
func remap(id string, mapping map[string]string) string {
	if to, ok := mapping[id]; ok {
		return to
	}
	return id
}

// applyIDRewrites performs the whole rewrite inside the caller's transaction:
// the id and scope_node columns and the body of every resource table, and
// the two subsystem tables that store a bare copy of an identifier — job_targets
// (target_id, and the scope_node frozen at acceptance) and pack_rows
// (scope_node).
//
// It touches no other column. jobs.created_by is a principal, packs.id is
// <publisher>/<name>, pack_rows.entity_id is the pack row's own host-minted
// identity, and a relay_id is deliberately not a ULID — none of them are
// governed by DAT-005a, and folding them would corrupt working references.
func applyIDRewrites(ctx context.Context, tx *sql.Tx, plan []IDRewrite) error {
	mapping := rewriteMapping(plan)

	for _, kind := range allKinds {
		table := string(kind)
		type stored struct{ id, scopeNode, body string }
		var rows []stored
		// Read the table out in full before writing any of it: the updates
		// below change primary keys, and mutating rows under a live cursor is
		// not something to rely on.
		cur, err := tx.QueryContext(ctx, `SELECT id, scope_node, body FROM `+table+` ORDER BY id ASC`)
		if err != nil {
			return fmt.Errorf("store: read %s for id canonicalization: %w", table, err)
		}
		for cur.Next() {
			var s stored
			if err := cur.Scan(&s.id, &s.scopeNode, &s.body); err != nil {
				cur.Close()
				return fmt.Errorf("store: scan %s for id canonicalization: %w", table, err)
			}
			rows = append(rows, s)
		}
		if err := cur.Err(); err != nil {
			cur.Close()
			return fmt.Errorf("store: read %s for id canonicalization: %w", table, err)
		}
		cur.Close()

		for _, s := range rows {
			newID := remap(s.id, mapping)
			newScope := remap(s.scopeNode, mapping)
			newBody := rewriteIDsInJSON(s.body, mapping)
			if newID == s.id && newScope == s.scopeNode && newBody == s.body {
				continue
			}
			// A rewrite that produced something that is no longer JSON would
			// corrupt the row past any later validator's ability to describe
			// it, so it is caught here, before the write.
			if !json.Valid([]byte(newBody)) {
				return fmt.Errorf("store: canonicalizing %s row %q produced a body that is not valid JSON", table, s.id)
			}
			if _, err := tx.ExecContext(ctx,
				`UPDATE `+table+` SET id = ?, scope_node = ?, body = ? WHERE id = ?`,
				newID, newScope, newBody, s.id,
			); err != nil {
				return fmt.Errorf("store: canonicalize %s row %q: %w", table, s.id, err)
			}
		}
	}

	// job_targets records which rows a Job acted on and where they sat when it
	// was accepted; it is never rewritten by a state transition, so it has to be
	// rewritten here or a completed Job would report targets that no longer
	// exist. pack_rows carries the scope node a pack's row is placed at. Neither
	// stores an identifier anywhere but these columns.
	//
	// events carries the scope node its subject resource sat under (events/1
	// EVT-012), which is the SOLE input to a subscriber's scope filtering
	// (EVT-120). A record left pointing at a renamed node would still be stored
	// but would match no principal's visible set — a durable audit record
	// (SEC-150) that no operator can ever see again. Only the placement column is
	// rewritten: the envelope's payload is the recorded fact itself, and this
	// migration exists to repair identifiers, not to edit history.
	for from, to := range mapping {
		for _, stmt := range []string{
			`UPDATE job_targets SET target_id = ? WHERE target_id = ?`,
			`UPDATE job_targets SET scope_node = ? WHERE scope_node = ?`,
			`UPDATE pack_rows SET scope_node = ? WHERE scope_node = ?`,
			`UPDATE events SET scope_node = ? WHERE scope_node = ?`,
		} {
			if _, err := tx.ExecContext(ctx, stmt, to, from); err != nil {
				return fmt.Errorf("store: canonicalize reference %q: %w", from, err)
			}
		}
	}
	return nil
}

// verifyAfterIDRewrite is the migration's safety net, run inside the same
// transaction as the rewrite so a failure discards all of it.
//
// It re-runs the very validators the write path runs — BuildFullScopeTree over
// the scope nodes, ValidateRows over the six scheduling-core kinds (which is what
// checks that every schedule/playlist/daypart/fallback/preset reference still
// resolves), and the automation id check — via validateAfterWrite, so the
// migration is judged by exactly the rule it exists to satisfy rather than by a
// second opinion written here. Then it confirms nothing anywhere still carries a
// rewritten identifier, which covers the references those validators do not
// reach: a row's scope_node, a job target, a pack row's placement.
//
// Re-planning last is the idempotence proof, asserted rather than assumed: the
// migration's own output must be a store this same planner finds nothing to do
// on.
func verifyAfterIDRewrite(ctx context.Context, tx *sql.Tx, plan []IDRewrite) error {
	// KindScopeNode selects BuildScopeTree, KindPlaylist selects ValidateRows
	// over the whole scheduling-core set (not just playlists), KindAutomation
	// the id check the rules compiler does not make, and KindScreen selects
	// ValidateIdentityRows over BOTH identity tables (a screen's device_id link
	// crosses them, so one kind selects the pair).
	for _, kind := range []Kind{KindScopeNode, KindPlaylist, KindAutomation, KindScreen} {
		// No placement of its own to resolve: the migration writes no new row, and
		// the rewritten scope_node columns are covered by the mapping sweep below.
		if err := validateAfterWrite(ctx, tx, kind, ""); err != nil {
			return fmt.Errorf("store: canonicalized row ids did not validate: %w", err)
		}
	}

	mapping := rewriteMapping(plan)
	for _, kind := range allKinds {
		table := string(kind)
		cur, err := tx.QueryContext(ctx, `SELECT id, scope_node, body FROM `+table)
		if err != nil {
			return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
		}
		for cur.Next() {
			var id, scopeNode, body string
			if err := cur.Scan(&id, &scopeNode, &body); err != nil {
				cur.Close()
				return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
			}
			for from := range mapping {
				if id == from || scopeNode == from || strings.Contains(body, `"`+from+`"`) {
					cur.Close()
					return fmt.Errorf("store: %s row %q still references the pre-canonicalization id %q", table, id, from)
				}
			}
		}
		if err := cur.Err(); err != nil {
			cur.Close()
			return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
		}
		cur.Close()
	}

	residual, blocked, err := planIDRewrites(ctx, tx)
	if err != nil {
		return err
	}
	if len(residual) > 0 || len(blocked) > 0 {
		return fmt.Errorf("store: canonicalizing row ids left %d id(s) still non-canonical and %d blocked", len(residual), len(blocked))
	}
	return nil
}

// PlanRowIDMigration reports every identifier MigrateRowIDs would rewrite,
// writing nothing. It is what an operator runs against a box before restarting
// the feeder on a build that enforces DAT-005a: an empty report means the
// restart is a no-op for the store, a non-empty one lists exactly what the next
// boot will change, and an *IDMigrationBlockedError means the next boot will
// refuse and the store needs a human before it is restarted.
func (s *Store) PlanRowIDMigration(ctx context.Context) (IDMigration, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	plan, blocked, err := planIDRewrites(ctx, s.db)
	if err != nil {
		return IDMigration{}, err
	}
	if len(blocked) > 0 {
		return IDMigration{}, &IDMigrationBlockedError{Blocked: blocked}
	}
	return IDMigration{Rewrites: plan}, nil
}

// MigrateRowIDs rewrites every stored identifier that violates DAT-005a, along
// with every reference to it, and returns what it changed. It is safe to call on
// every boot: a store that already conforms is not written to at all — no
// transaction is opened, no generation is bumped, no commit hook fires — so the
// only store it can alter is one that was write-dead to begin with.
//
// It never creates or deletes a row and never touches a field other than an
// identifier. Everything happens in one transaction that ends by re-running the
// write path's own validators, so a rewrite that would strand a reference
// commits nothing at all and the caller gets the failure instead of a
// half-migrated store.
//
// The generation IS advanced, exactly once, when anything changed: the row ids
// are part of the desired state a relay caches by generation, so a migrated
// store that kept its old generation would leave connected relays serving the
// pre-migration ids indefinitely.
func (s *Store) MigrateRowIDs(ctx context.Context) (IDMigration, error) {
	// Plan under the read lock first, purely so a conforming store never even
	// takes the write lock. The write path re-plans under its own lock, so this
	// is an optimization and not the decision.
	if m, err := s.PlanRowIDMigration(ctx); err != nil || len(m.Rewrites) == 0 {
		return m, err
	}

	var applied []IDRewrite
	if err := s.runWriteTx(ctx, func(tx *sql.Tx) error {
		plan, blocked, err := planIDRewrites(ctx, tx)
		if err != nil {
			return err
		}
		if len(blocked) > 0 {
			return &IDMigrationBlockedError{Blocked: blocked}
		}
		if len(plan) == 0 {
			return nil
		}
		if err := applyIDRewrites(ctx, tx, plan); err != nil {
			return err
		}
		if err := verifyAfterIDRewrite(ctx, tx, plan); err != nil {
			return err
		}
		if err := bumpGeneration(ctx, tx); err != nil {
			return err
		}
		applied = plan
		return nil
	}); err != nil {
		return IDMigration{}, err
	}

	if len(applied) > 0 {
		// runWriteTx does not fire the commit hook (writeTx does), so a
		// migration that changed the desired state nudges connected relays
		// itself — and one that changed nothing stays silent.
		s.hookMu.Lock()
		hook := s.onCommit
		s.hookMu.Unlock()
		if hook != nil {
			hook()
		}
	}
	return IDMigration{Rewrites: applied}, nil
}
