package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/maaxton/waiveo-next/internal/shared/ulid"
)

// This file canonicalizes row identifiers a build that predates DAT-005a
// enforcement left behind.
//
// Why it has to exist: every write validates the RESULTING full row-set
// (validateAfterWrite), not just the row being written. Once DAT-005a is
// enforced, a single stored row whose id is not a canonical ULID makes the whole
// store WRITE-DEAD — readable, and every subsequent create/update/delete fails
// with ROW_ID_INVALID for a row the caller never touched. A store seeded by an
// older build is exactly that, so it cannot be unstuck by authoring alone; the
// illegal ids have to be rewritten out from under the validator.
//
// Why it rewrites rather than reseeds: the same store holds authored content. A
// deployed box's playlists, schedules and automations are the user's, and a
// scope node seeded on day one is the node their authored rows hang off. Wiping
// and reseeding would destroy authored data to fix a syntax rule, which the
// platform's never-wipe discipline forbids outright. So the migration preserves
// every row and every field, and only replaces the identifier text.
//
// The replacement is a FOLD, not a fresh mint (foldToCanonicalULID): the
// characters Crockford base32 excludes are mapped onto the symbols they were
// excluded in favour of. That gives three properties a fresh ulid.New could not:
// the new id is derived from the old one, so an operator reading a log or a
// backup can still correlate them; the mapping is deterministic, so the same
// store migrates to the same ids on every run and on every box; and a store
// seeded by the older build converges on exactly the ids a freshly seeded store
// carries today (SeedDemo's constants were regenerated by this same
// substitution), so a migrated box and a fresh box are not two divergent
// worlds.
//
// The fold has one property the rest of the file leans on: its OUTPUT is always
// a canonical ULID, and only a NON-canonical id is ever an input. So no rewrite
// target can also be a rewrite source — the mapping never chains. That is what
// makes a single unordered replacement pass correct, and what makes the whole
// migration idempotent: run it on its own output and there is nothing left to
// match.

// crockfordFold maps each character canonical Crockford base32 excludes onto the
// symbol it was excluded in favour of. I, L and O are Crockford's own documented
// decoding aliases (they decode as 1, 1 and 0). U is not an alias in the spec —
// Crockford drops it outright — so mapping it to V is this repository's
// convention, the same substitution the seed identifiers were regenerated with,
// and V is the symbol that takes U's place in the alphabet.
var crockfordFold = map[byte]byte{
	'I': '1',
	'L': '1',
	'O': '0',
	'U': 'V',
}

// foldToCanonicalULID rewrites id into a canonical ULID by upper-casing it
// (Crockford decoding is case-insensitive) and substituting the excluded
// characters. ok is false when the result still is not canonical — a wrong
// length, a character outside the alphabet and outside crockfordFold, or a
// leading symbol above 7 (which would overflow the 48-bit timestamp field). A
// fold is only ever attempted, and only ever needed, for an id ulid.Valid
// already rejected.
func foldToCanonicalULID(id string) (string, bool) {
	out := []byte(strings.ToUpper(id))
	for i, c := range out {
		if sub, ok := crockfordFold[c]; ok {
			out[i] = sub
		}
	}
	folded := string(out)
	if !ulid.Valid(folded) {
		return "", false
	}
	return folded, true
}

// IDRewrite is one identifier the migration replaced (or, from
// PlanRowIDMigration, would replace). Kind names the table the identifier
// addresses, and — this is the whole of the reference invariant — EVERY rewrite
// renames a stored ROW. References to that row (a child's parent_id, a
// daypart's playlist_id, a job target) are carried along by the same entry;
// there is no entry that moves a reference on its own. Enforced, not merely
// intended: see assertPlanRenamesStoredRows, which the planner runs over every
// plan it produces.
type IDRewrite struct {
	Kind Kind
	From string
	To   string
}

// DanglingParent is one scope-node parent_id that names no stored scope node —
// a reference the data model would refuse to create today and that an older
// build's store can nevertheless be holding (see the "reported, never
// rewritten" note on planIDRewrites).
type DanglingParent struct {
	ChildID  string
	ParentID string
}

// IDMigration reports the identifiers a run rewrote. A zero-length Rewrites
// means the store already conformed and nothing was written.
//
// Dangling is a REPORT, never a plan: the parent references pointing at no row,
// as the store stands when the call returns. Nothing in the migration acts on
// one — no entry is ever planned to move a reference by itself — though a
// dangling value CAN change spelling when it happens to name a row in another
// table that is being renamed, which is why the report is taken after the
// rewrite rather than before it.
//
// It is populated whether or not anything was rewritten, because a store with
// nothing to canonicalize can still be missing the node its own rows name —
// which is the state that took every owner-gated route on a box down while the
// box looked healthy.
type IDMigration struct {
	Rewrites []IDRewrite
	Dangling []DanglingParent
}

// BlockedID names one identifier the migration refused to rewrite, and why.
type BlockedID struct {
	Kind   Kind
	ID     string
	Reason string
}

// IDMigrationBlockedError is returned when at least one identifier cannot be
// folded, or would fold onto an id its table already holds. The migration is
// all-or-nothing: on this error NOTHING was written and the store is exactly as
// it was. It is deliberately not a partial success — an id this fold cannot
// derive a canonical ULID from did not come from SeedDemo or from any api/1
// write (the api layer mints every id server-side), so it is evidence of
// something unaccounted for, and inventing an unrelated identifier for it would
// silently sever whatever authored it from its own data.
type IDMigrationBlockedError struct {
	Blocked []BlockedID
}

func (e *IDMigrationBlockedError) Error() string {
	parts := make([]string, 0, len(e.Blocked))
	for _, b := range e.Blocked {
		parts = append(parts, fmt.Sprintf("%s id %q: %s", b.Kind, b.ID, b.Reason))
	}
	return "store: cannot canonicalize row ids (DAT-005a): " + strings.Join(parts, "; ")
}

// planIDRewrites reads every stored identifier and works out which ones violate
// DAT-005a and what each would become. It writes nothing, and is the single
// source of the plan for both the read-only report and the migrating write — so
// what an operator is shown is computed by the same code that later acts.
//
// The plan is every row's own id across every resource table (for preset_batches
// the id column holds the body's preset_id, DAT-005's byte-exact exception, so
// it is reached the same way). Nothing else. A reference is rewritten only
// because the ROW IT NAMES is being renamed in the same transaction, by the same
// entry, through applyIDRewrites' mapping — which is what makes "rename a row"
// and "repoint everything at it" one indivisible act rather than two hopeful
// ones.
//
// # Dangling scope-node parents are REPORTED, never rewritten
//
// A scope-node parent_id is the ONLY reference the data model lets dangle: an
// absent parent is a subtree boundary to the subtree-tolerant builder, so a
// parent_id need not appear as a stored row id. Every other reference is
// required by ValidateRows to resolve to a present row.
//
// This function used to FOLD such a value — rewriting a reference with no row
// behind it into its canonical spelling, on the reasoning that a non-canonical
// id can never again name a row anyone could create, so the folded form is the
// only value that could ever resolve. The reasoning is sound and the act is
// still wrong, for two reasons that outweigh it. It emits an entry
// indistinguishable, in the plan and in the boot log, from a real row rename —
// which is exactly the ambiguity that let a box's boot log be read as proof that
// a node existed when what the log recorded was a pointer to a node that never
// had. And it turns a VISIBLE dangle into a canonical-looking one: same broken
// reference, now wearing the spelling of a healthy id, with nothing left in the
// log to say the store is missing a row.
//
// So a dangle is reported and left byte-identical. Repairing it means CREATING
// the row it names — the one act that makes the reference true — and that is
// orgroot.go's job, which mints the row and repoints the reference in a single
// transaction. Rewriting a reference is legitimate exactly when the row moves
// with it, which assertPlanRenamesStoredRows holds every plan to before it is
// either reported or applied.
func planIDRewrites(ctx context.Context, q queryer) ([]IDRewrite, []BlockedID, []DanglingParent, error) {
	var plan []IDRewrite
	var blocked []BlockedID

	for _, kind := range allKinds {
		ids, err := readIDs(ctx, q, string(kind))
		if err != nil {
			return nil, nil, nil, err
		}
		// Every id the table already holds, plus every id a rewrite in this
		// table is about to claim: a fold landing on either would collide on
		// the primary key, and picking a winner would silently merge two rows.
		claimed := make(map[string]bool, len(ids))
		for _, id := range ids {
			claimed[id] = true
		}
		for _, id := range ids {
			if ulid.Valid(id) {
				continue
			}
			folded, ok := foldToCanonicalULID(id)
			if !ok {
				blocked = append(blocked, BlockedID{Kind: kind, ID: id, Reason: "cannot be folded into a canonical ULID"})
				continue
			}
			if claimed[folded] {
				blocked = append(blocked, BlockedID{Kind: kind, ID: id, Reason: fmt.Sprintf("would fold onto %q, which %s already holds", folded, kind)})
				continue
			}
			claimed[folded] = true
			plan = append(plan, IDRewrite{Kind: kind, From: id, To: folded})
		}
	}

	dangling, err := danglingScopeNodeParents(ctx, q)
	if err != nil {
		return nil, nil, nil, err
	}
	if err := assertPlanRenamesStoredRows(ctx, q, plan); err != nil {
		return nil, nil, nil, err
	}

	sort.Slice(plan, func(i, j int) bool {
		if plan[i].Kind != plan[j].Kind {
			return plan[i].Kind < plan[j].Kind
		}
		return plan[i].From < plan[j].From
	})
	sort.Slice(blocked, func(i, j int) bool {
		if blocked[i].Kind != blocked[j].Kind {
			return blocked[i].Kind < blocked[j].Kind
		}
		return blocked[i].ID < blocked[j].ID
	})
	return plan, blocked, dangling, nil
}

// assertPlanRenamesStoredRows is THE REFERENCE INVARIANT, checked in the one
// place it is decidable: on the plan, against the store as it still stands.
//
// Every entry must rename a row its table actually holds. That is the whole of
// what makes a rewrite safe — applyIDRewrites moves a row's id and every quoted
// occurrence of it through ONE flat mapping, so a reference is repointed
// precisely because the row it names moved with it, in the same transaction. An
// entry whose From names no row is a reference moving on its own: the store
// keeps the identical broken pointer in a new spelling, and the boot logs a line
// no operator can tell from a real row rename. That is the defect this file's
// planner was changed to stop emitting, and this is the assertion that keeps it
// from coming back.
//
// # Why the plan, and not the state afterwards
//
// The obvious alternative — compare the dangling parents before and after, and
// refuse if the rewrite MANUFACTURED one — cannot be written correctly by value,
// and by value is the only way the after-state offers. A parent_id that dangles
// but happens to equal some other table's row id is carried into that row's
// folded spelling by that table's entirely legitimate entry: the reference was
// broken before, is broken after, and merely changed spelling, which a value
// comparison reads as newly stranded and refuses. Refusing there aborts the
// whole transaction, which at boot is a fatal — turning a store that migrated
// cleanly into one that can never start.
//
// Nor would keying by (child, parent) rescue it, because the after-state simply
// does not carry the distinction: applyIDRewrites moves an id column and its
// references from the same mapping, so a reference whose target row was renamed
// always moves with it, and a post-rewrite dangle is therefore ALWAYS an
// inherited one. Provenance — did this entry name a row? — is the thing that
// actually differs, and it is only legible before the rewrite.
//
// Being decidable in the plan has a second virtue, and it is not a small one:
// `waiveo-feeder -store-check` runs this same planner, so an operator's dry run
// predicts the refusal instead of printing a reassuring plan for a boot that
// will fatal.
//
// The stored ids are re-read here rather than threaded out of the loop above on
// purpose. An assertion fed the very map it is judging asserts nothing; this one
// asks the database again, so it still holds if the plan later grows a
// population built from something other than a table scan.
func assertPlanRenamesStoredRows(ctx context.Context, q queryer, plan []IDRewrite) error {
	stored := make(map[Kind]map[string]bool)
	for _, rw := range plan {
		ids, ok := stored[rw.Kind]
		if !ok {
			got, err := readIDs(ctx, q, string(rw.Kind))
			if err != nil {
				return err
			}
			ids = make(map[string]bool, len(got))
			for _, id := range got {
				ids[id] = true
			}
			stored[rw.Kind] = ids
		}
		if !ids[rw.From] {
			return fmt.Errorf("store: the id canonicalization plan would move a reference on its own: planned %s %q -> %q, which renames no stored row", rw.Kind, rw.From, rw.To)
		}
	}
	return nil
}

// danglingScopeNodeParents reports every scope node whose parent_id names no
// stored scope-node row, in child-id order.
//
// The membership test is against the ID COLUMN of scope_nodes, not against the
// `id` inside each body: the column is the primary key applyIDRewrites renames
// and the thing a reference must resolve to. The two are equal by construction
// (Create takes the column from the body's own identity field and Update never
// rewrites it), and testing the one that is load-bearing is the cheaper thing to
// be right about.
//
// Canonicality is deliberately NOT part of the test. A parent_id that names a
// row is fine whether or not it is a canonical ULID — if that row is being
// renamed, the reference rides along with it — and a parent_id that names
// nothing is a dangle whether or not it LOOKS like a healthy identifier. The
// pre-existing dangle on a real box was a perfectly canonical ULID.
func danglingScopeNodeParents(ctx context.Context, q queryer) ([]DanglingParent, error) {
	ids, err := readIDs(ctx, q, string(KindScopeNode))
	if err != nil {
		return nil, err
	}
	stored := make(map[string]bool, len(ids))
	for _, id := range ids {
		stored[id] = true
	}
	nodes, err := readScopeNodes(ctx, q)
	if err != nil {
		return nil, err
	}
	var out []DanglingParent
	for _, n := range nodes {
		if n.ParentID == nil || stored[*n.ParentID] {
			continue
		}
		out = append(out, DanglingParent{ChildID: n.ID, ParentID: *n.ParentID})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ChildID < out[j].ChildID })
	return out, nil
}

// rewriteMapping flattens a plan into the old→new lookup the replacement pass
// applies. Distinct tables can legitimately share a From (the same folded value
// then names a row in each), which is why the plan is keyed by table but the
// mapping is not.
func rewriteMapping(plan []IDRewrite) map[string]string {
	m := make(map[string]string, len(plan))
	for _, rw := range plan {
		m[rw.From] = rw.To
	}
	return m
}

// rewriteIDsInJSON replaces every complete JSON string value that equals a
// rewritten identifier. Matching on the quoted token is what makes this precise
// rather than a blind search-and-replace: the closing quote anchors the match,
// so a rewritten id can never be substituted into the middle of a longer string.
//
// It is deliberately key-agnostic. Reference identifiers appear under a dozen
// different keys (scope_node, parent_id, schedule_id, playlist_id,
// preset_batch_id, fallback_id, an automation action's preset_id) and at
// arbitrary depth inside a rule body's nested and/or/not conditions and branch
// actions. Enumerating those keys would make the migration silently wrong the
// day a new one is added; matching the VALUE cannot miss one. Nothing is at risk
// from over-reach, because the only values it looks for are identifiers that
// were unusable by definition.
//
// The one place an identifier can hide from this is inside a longer string — a
// rules/1 expression literal such as state('…'). Those hold device-plane entity
// ids, which live in a different, in-memory id space and are never rewritten
// here, so no such value is ever in the mapping.
//
// Replacement order does not matter: no To is ever a From (see the file header),
// so the passes cannot chain.
func rewriteIDsInJSON(body string, mapping map[string]string) string {
	for from, to := range mapping {
		body = strings.ReplaceAll(body, `"`+from+`"`, `"`+to+`"`)
	}
	return body
}

// remap returns the rewritten form of an identifier, or the identifier
// unchanged when it is not one the plan touches.
func remap(id string, mapping map[string]string) string {
	if to, ok := mapping[id]; ok {
		return to
	}
	return id
}

// applyIDRewrites performs the whole rewrite inside the caller's transaction:
// the id and scope_node columns and the body of every resource table, and
// the two subsystem tables that store a bare copy of an identifier — job_targets
// (target_id, and the scope_node frozen at acceptance) and pack_rows
// (scope_node).
//
// It touches no other column. jobs.created_by is a principal, packs.id is
// <publisher>/<name>, pack_rows.entity_id is the pack row's own host-minted
// identity, and a relay_id is deliberately not a ULID — none of them are
// governed by DAT-005a, and folding them would corrupt working references.
func applyIDRewrites(ctx context.Context, tx *sql.Tx, plan []IDRewrite) error {
	mapping := rewriteMapping(plan)

	for _, kind := range allKinds {
		table := string(kind)
		type stored struct{ id, scopeNode, body string }
		var rows []stored
		// Read the table out in full before writing any of it: the updates
		// below change primary keys, and mutating rows under a live cursor is
		// not something to rely on.
		cur, err := tx.QueryContext(ctx, `SELECT id, scope_node, body FROM `+table+` ORDER BY id ASC`)
		if err != nil {
			return fmt.Errorf("store: read %s for id canonicalization: %w", table, err)
		}
		for cur.Next() {
			var s stored
			if err := cur.Scan(&s.id, &s.scopeNode, &s.body); err != nil {
				cur.Close()
				return fmt.Errorf("store: scan %s for id canonicalization: %w", table, err)
			}
			rows = append(rows, s)
		}
		if err := cur.Err(); err != nil {
			cur.Close()
			return fmt.Errorf("store: read %s for id canonicalization: %w", table, err)
		}
		cur.Close()

		for _, s := range rows {
			newID := remap(s.id, mapping)
			newScope := remap(s.scopeNode, mapping)
			newBody := rewriteIDsInJSON(s.body, mapping)
			if newID == s.id && newScope == s.scopeNode && newBody == s.body {
				continue
			}
			// A rewrite that produced something that is no longer JSON would
			// corrupt the row past any later validator's ability to describe
			// it, so it is caught here, before the write.
			if !json.Valid([]byte(newBody)) {
				return fmt.Errorf("store: canonicalizing %s row %q produced a body that is not valid JSON", table, s.id)
			}
			if _, err := tx.ExecContext(ctx,
				`UPDATE `+table+` SET id = ?, scope_node = ?, body = ? WHERE id = ?`,
				newID, newScope, newBody, s.id,
			); err != nil {
				return fmt.Errorf("store: canonicalize %s row %q: %w", table, s.id, err)
			}
		}
	}

	// job_targets records which rows a Job acted on and where they sat when it
	// was accepted; it is never rewritten by a state transition, so it has to be
	// rewritten here or a completed Job would report targets that no longer
	// exist. pack_rows carries the scope node a pack's row is placed at. Neither
	// stores an identifier anywhere but these columns.
	//
	// events carries the scope node its subject resource sat under (events/1
	// EVT-012), which is the SOLE input to a subscriber's scope filtering
	// (EVT-120). A record left pointing at a renamed node would still be stored
	// but would match no principal's visible set — a durable audit record
	// (SEC-150) that no operator can ever see again. Only the placement column is
	// rewritten: the envelope's payload is the recorded fact itself, and this
	// migration exists to repair identifiers, not to edit history.
	for from, to := range mapping {
		for _, stmt := range []string{
			`UPDATE job_targets SET target_id = ? WHERE target_id = ?`,
			`UPDATE job_targets SET scope_node = ? WHERE scope_node = ?`,
			`UPDATE pack_rows SET scope_node = ? WHERE scope_node = ?`,
			`UPDATE events SET scope_node = ? WHERE scope_node = ?`,
		} {
			if _, err := tx.ExecContext(ctx, stmt, to, from); err != nil {
				return fmt.Errorf("store: canonicalize reference %q: %w", from, err)
			}
		}
	}
	return nil
}

// idMigrationVerifyKinds is the one inventory of the validators the id
// migration is judged by — one representative kind per validator, since
// rowSetFaults's scheduling arm covers all seven scheduling tables and its
// identity arm both identity tables. The pre-rewrite capture and the
// post-rewrite verification walk THIS list, not two transcriptions of it: a kind
// captured but not verified is a diff nobody uses, and a kind verified but not
// captured is a boot-time brick of exactly the shape priorfaults.go exists to
// prevent.
var idMigrationVerifyKinds = []Kind{KindScopeNode, KindPlaylist, KindAutomation, KindScreen}

// verifyAfterIDRewrite is the migration's safety net, run inside the same
// transaction as the rewrite so a failure discards all of it.
//
// It re-runs the very validators the write path runs — BuildFullScopeTree over
// the scope nodes, ValidateRows over the six scheduling-core kinds (which is what
// checks that every schedule/playlist/daypart/fallback/preset reference still
// resolves), and the automation id check — via validateAfterWrite, so the
// migration is judged by exactly the rule it exists to satisfy rather than by a
// second opinion written here. Then it confirms nothing anywhere still carries a
// rewritten identifier, which covers the references those validators do not
// reach: a row's scope_node, a job target, a pack row's placement.
//
// Re-planning last is the idempotence proof, asserted rather than assumed: the
// migration's own output must be a store this same planner finds nothing to do
// on.
//
// The reference invariant — no rewrite may move a reference whose row is not
// moving with it — is NOT re-checked here, because it is not decidable here. It
// lives in assertPlanRenamesStoredRows, which the planner runs before the
// rewrite and whose doc comment sets out why the after-state cannot tell an
// inherited dangle from a caused one.
func verifyAfterIDRewrite(ctx context.Context, tx *sql.Tx, plan []IDRewrite, prior map[Kind]priorFaults) error {
	// KindScopeNode selects BuildScopeTree, KindPlaylist selects ValidateRows
	// over the whole scheduling-core set (not just playlists), KindAutomation
	// the id check the rules compiler does not make, and KindScreen selects
	// ValidateIdentityRows over BOTH identity tables (a screen's device_id link
	// crosses them, so one kind selects the pair).
	for _, kind := range idMigrationVerifyKinds {
		// No placement of its own to resolve: the migration writes no new row, and
		// the rewritten scope_node columns are covered by the mapping sweep below.
		//
		// Judged against the faults the store carried BEFORE the rewrite (captured
		// by MigrateRowIDs), for the reason priorfaults.go sets out and with one
		// extra edge to it here: this runs at BOOT. A store holding a row an
		// older build accepted and a current validator does not — an inline slide
		// with an empty layer stack, say — would otherwise fail its id migration
		// permanently, and a migration that cannot complete is a store that cannot
		// be written to at all. The migration must still be refused for anything
		// IT broke, which is exactly what the difference reports.
		if err := validateAfterWrite(ctx, tx, kind, "", prior[kind]); err != nil {
			return fmt.Errorf("store: canonicalized row ids did not validate: %w", err)
		}
	}

	mapping := rewriteMapping(plan)
	for _, kind := range allKinds {
		table := string(kind)
		cur, err := tx.QueryContext(ctx, `SELECT id, scope_node, body FROM `+table)
		if err != nil {
			return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
		}
		for cur.Next() {
			var id, scopeNode, body string
			if err := cur.Scan(&id, &scopeNode, &body); err != nil {
				cur.Close()
				return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
			}
			for from := range mapping {
				if id == from || scopeNode == from || strings.Contains(body, `"`+from+`"`) {
					cur.Close()
					return fmt.Errorf("store: %s row %q still references the pre-canonicalization id %q", table, id, from)
				}
			}
		}
		if err := cur.Err(); err != nil {
			cur.Close()
			return fmt.Errorf("store: verify %s after id canonicalization: %w", table, err)
		}
		cur.Close()
	}

	residual, blocked, _, err := planIDRewrites(ctx, tx)
	if err != nil {
		return err
	}
	if len(residual) > 0 || len(blocked) > 0 {
		return fmt.Errorf("store: canonicalizing row ids left %d id(s) still non-canonical and %d blocked", len(residual), len(blocked))
	}
	return nil
}

// PlanRowIDMigration reports every identifier MigrateRowIDs would rewrite,
// writing nothing. It is what an operator runs against a box before restarting
// the feeder on a build that enforces DAT-005a: an empty report means the
// restart is a no-op for the store, a non-empty one lists exactly what the next
// boot will change, and an *IDMigrationBlockedError means the next boot will
// refuse and the store needs a human before it is restarted.
//
// It also reports the parent references that name no row (Dangling), which the
// migration will NOT touch — a store can be perfectly canonical and still be
// missing a node the rest of it points at.
func (s *Store) PlanRowIDMigration(ctx context.Context) (IDMigration, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	plan, blocked, dangling, err := planIDRewrites(ctx, s.db)
	if err != nil {
		return IDMigration{}, err
	}
	if len(blocked) > 0 {
		return IDMigration{}, &IDMigrationBlockedError{Blocked: blocked}
	}
	return IDMigration{Rewrites: plan, Dangling: dangling}, nil
}

// MigrateRowIDs rewrites every stored identifier that violates DAT-005a, along
// with every reference to it, and returns what it changed. It is safe to call on
// every boot: a store that already conforms is not written to at all — no
// transaction is opened, no generation is bumped, no commit hook fires — so the
// only store it can alter is one that was write-dead to begin with.
//
// It never creates or deletes a row and never touches a field other than an
// identifier. Everything happens in one transaction that ends by re-running the
// write path's own validators, so a rewrite that would strand a reference
// commits nothing at all and the caller gets the failure instead of a
// half-migrated store.
//
// The generation IS advanced, exactly once, when anything changed: the row ids
// are part of the desired state a relay caches by generation, so a migrated
// store that kept its old generation would leave connected relays serving the
// pre-migration ids indefinitely.
func (s *Store) MigrateRowIDs(ctx context.Context) (IDMigration, error) {
	// Plan under the read lock first, purely so a conforming store never even
	// takes the write lock. The write path re-plans under its own lock, so this
	// is an optimization and not the decision.
	if m, err := s.PlanRowIDMigration(ctx); err != nil || len(m.Rewrites) == 0 {
		return m, err
	}

	var applied []IDRewrite
	var dangling []DanglingParent
	if err := s.runWriteTx(ctx, func(tx *sql.Tx) error {
		plan, blocked, dangles, err := planIDRewrites(ctx, tx)
		if err != nil {
			return err
		}
		if len(blocked) > 0 {
			return &IDMigrationBlockedError{Blocked: blocked}
		}
		// Reported from the write path's own reading, not from the read-lock plan
		// above, so what the caller logs is what the transaction actually saw. On
		// a store with nothing to rewrite this reading is already final; when
		// there IS a rewrite it is re-taken below, after it.
		dangling = dangles
		if len(plan) == 0 {
			return nil
		}
		// Captured BEFORE the rewrite, one reading per validator the verification
		// below runs, so the migration is judged on the faults it introduced
		// (priorfaults.go).
		prior := make(map[Kind]priorFaults, len(idMigrationVerifyKinds))
		for _, kind := range idMigrationVerifyKinds {
			p, err := capturePriorFaults(ctx, tx, kind)
			if err != nil {
				return err
			}
			prior[kind] = p
		}
		if err := applyIDRewrites(ctx, tx, plan); err != nil {
			return err
		}
		if err := verifyAfterIDRewrite(ctx, tx, plan, prior); err != nil {
			return err
		}
		// Re-read, so the report describes the store the transaction is about to
		// commit rather than the one it opened on. A dangling parent_id that
		// happens to name a row in another table is carried into that row's new
		// spelling by that row's own rename, and a child's id can itself be
		// renamed — so the pre-rewrite reading would print identifiers the store no
		// longer holds. A log line an operator cannot find in the store is the
		// exact failure this whole change is about.
		if dangling, err = danglingScopeNodeParents(ctx, tx); err != nil {
			return err
		}
		if err := bumpGeneration(ctx, tx); err != nil {
			return err
		}
		applied = plan
		return nil
	}); err != nil {
		return IDMigration{}, err
	}

	if len(applied) > 0 {
		// runWriteTx does not fire the commit hook (writeTx does), so a
		// migration that changed the desired state nudges connected relays
		// itself — and one that changed nothing stays silent.
		s.hookMu.Lock()
		hook := s.onCommit
		s.hookMu.Unlock()
		if hook != nil {
			hook()
		}
	}
	return IDMigration{Rewrites: applied, Dangling: dangling}, nil
}
