// The api/1 console client — public surface.
//
// `createApi()` builds the whole typed surface over one client; the individual
// types and error classes are re-exported for pages, tests, and the ui-schema
// data sources that render over these resources.

export {
  createAuthModule,
  secondFactorRequired,
  type AuthModule,
  type SessionSummary,
  type LoginRequest,
  type ClaimRequest,
  type PrincipalKind,
  type Role,
  type AAL,
  type TotpEnrollment,
  type TotpCredential,
} from "./auth";

export {
  ApiClient,
  ApiError,
  RevisionConflictError,
  API_BASE,
  CSRF_COOKIE,
  CSRF_HEADER,
  readCookie,
  type Problem,
  type ErrorCode,
  type ValidationFieldError,
  type FieldErrors,
  type Read,
  type ApiClientOptions,
} from "./client";

export {
  paginate,
  collectPages,
  type Page,
  type PageFetcher,
} from "./pagination";

export {
  createApi,
  updateWithReview,
  etagForRevision,
  normalizePlaylistItem,
  PLAYLIST_ITEM_SOURCES,
  type WaiveoApi,
  type ResourceModule,
  type AutomationsModule,
  type ContentModule,
  type Resource,
  type ListParams,
  type UpdateOutcome,
  type ScopeNode,
  type ScopeNodeCreate,
  type ScopeNodeUpdate,
  type Automation,
  type AutomationCreate,
  type AutomationUpdate,
  type AutomationRunResult,
  type Schedule,
  type ScheduleCreate,
  type ScheduleUpdate,
  type Daypart,
  type DaypartCreate,
  type DaypartUpdate,
  type Playlist,
  type PlaylistCreate,
  type PlaylistUpdate,
  type PlaylistItem,
  type PlaylistItemSource,
  type PlaylistInlineSlide,
  type ContentUploadResult,
  type ContentAsset,
  type Screen,
  type ScreenCreate,
  type ScreenUpdate,
  type PairingCodeResult,
  type ScreensModule,
  type ScreenNow,
  type ScreenNowRequest,
  type ScreenStatus,
  type ScreenStatusModule,
  type Variable,
  type VariableCreate,
  type VariableUpdate,
  type VariableValue,
} from "./resources";

export {
  createDevicePlaneModules,
  deviceFacts,
  launchableApps,
  type DevicePlaneModules,
  type DeviceFacts,
  type ListOnlyModule,
  type DevicesModule,
  type EntitiesModule,
  type Device,
  type Entity,
  type EntityCommandRequest,
  type EntityCommandResult,
  type AdoptedDevice,
  type AdoptedDeviceCreate,
  type AdoptedDeviceUpdate,
  type AdoptedDeviceEntity,
} from "./devices";

export {
  createCastsModule,
  validateSlide,
  validateCastSlides,
  validateNavTargets,
  SLIDE_CANVAS_WIDTH,
  SLIDE_CANVAS_HEIGHT,
  LAYER_KINDS,
  WIDGET_LAYER_KINDS,
  DERIVE_KINDS,
  DERIVE_FILL_KINDS,
  deriveNeedsRender,
  LABEL_LAYER_KINDS,
  CONTENT_LAYER_KINDS,
  WEATHER_TOKENS,
  ENTITY_STATE_TOKEN,
  isLabelKind,
  isContentKind,
  isInteractiveLayer,
  navItemRects,
  INTERACTIVE_LAYER_KINDS,
  PING_NAME_PATTERN,
  PING_NAME_MAX,
  NAV_ITEMS_MAX,
  MIN_INTERACTIVE_SIDE,
  type CastsModule,
  type Cast,
  type CastCreate,
  type CastUpdate,
  type CastSlide,
  type SlideLayer,
  type LayerKind,
  type WidgetLayerKind,
  type DeriveKind,
  type DeriveFillKind,
  type DeriveSpec,
  type DeriveFill,
  type DeriveShadow,
  type DeriveBorder,
  type ContentLayerKind,
  type LayerAlign,
  type NavItem,
  type SlideProblem,
} from "./casts";

export {
  createBackupModule,
  createJobsModule,
  jobIsTerminal,
  jobFailureDetail,
  TERMINAL_JOB_STATES,
  type BackupModule,
  type JobsModule,
  type Job,
  type WorkspaceArchive,
  type WorkspaceArchiveList,
} from "./backup";

export {
  createDiagnosticsModule,
  LOG_LEVELS,
  type DiagnosticsModule,
  type PlatformLogRecord,
  type PlatformLogPage,
  type PlatformLogQuery,
  type LogLevel,
  type SystemHealth,
  type ServiceHealth,
  type StorageHealth,
  type RelayHealth,
  type ScreenHealth,
  type RestartAcceptance,
} from "./diagnostics";

export {
  createPacksModule,
  packData,
  encodePackPagePath,
  TRUST_CHANNELS,
  type PacksModule,
  type Pack,
  type PackManifest,
  type PackManifestPage,
  type PackManifestCollection,
  type PackManifestField,
  type PackInstallResult,
  type PackInstallRecord,
  type CatalogEntry,
  type CatalogSource,
  type PackUpdateAction,
  type PackUpdateAvailability,
  type PackUpdateResult,
  type MarketplaceRef,
  type TrustChannel,
  type PackRow,
  type PackRowWrite,
} from "./packs";
