package auth

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/maaxton/waiveo-next/internal/events"
	"github.com/maaxton/waiveo-next/internal/relay/reenroll"
)

// Grant purposes (SEC-030). One generic, purpose-scoped, redeemable record
// stands behind enrollment, pairing, invites, credential reset and recovery —
// the contract is explicit that these are not seven mechanisms but one.
const (
	PurposeSetup           = "setup"
	PurposeInvite          = "invite"
	PurposePairing         = "pairing"
	PurposeRelayClaim      = "relay-claim"
	PurposeCredentialReset = "credential-reset"
	PurposeRecovery        = "recovery"
	PurposeSupport         = "support"
)

var validPurposes = map[string]struct{}{
	PurposeSetup: {}, PurposeInvite: {}, PurposePairing: {}, PurposeRelayClaim: {},
	PurposeCredentialReset: {}, PurposeRecovery: {}, PurposeSupport: {},
}

// ValidPurpose reports whether p is one of SEC-030's seven grant purposes.
func ValidPurpose(p string) bool {
	_, ok := validPurposes[p]
	return ok
}

// Redemption modes (SEC-031). `one-time` is the DEFAULT and the only mode this
// increment mints; `multi` is schema-legal and carries its own bound in
// max_redemptions, so the atomic consume below is already written against a
// count rather than a boolean.
const (
	RedemptionOneTime = "one-time"
	RedemptionMulti   = "multi"
)

// Issuance channels (SEC-030's `issued_via`).
const (
	IssuedViaAPI     = "api"
	IssuedViaConsole = "console"
)

// GrantRow is SEC-030's grant record. `ttl` is carried as TTLMs (epoch-relative
// milliseconds) rather than an ISO-8601 duration string, so an expiry check is
// integer arithmetic against the injected clock rather than a parse; the wire
// shape converts. The code itself is NOT a field: only CodeHash is stored, so a
// database read can never yield a redeemable code.
type GrantRow struct {
	GrantID                string
	Purpose                string
	ResultingPrincipalKind string
	ScopeNode              string
	Labels                 map[string]string
	Role                   Role
	TTLMs                  int64
	RedemptionMode         string
	MaxRedemptions         int
	RedemptionCount        int
	ConsentRecord          string
	IssuedVia              string
	IssuedAt               int64
	CodeHash               string
}

// ExpiresAt is the instant this grant's ttl elapses (SEC-032/035).
func (g GrantRow) ExpiresAt() int64 { return g.IssuedAt + g.TTLMs }

// Grant TTL defaults. SEC-032: a `credential-reset` or `recovery` grant SHOULD
// be about 15 minutes; other purposes MAY use a longer ttl suited to their own
// flow. A `setup` grant is generated by the installer and read off a printed
// card or a screen (SEC-120), so it must outlive an unattended first boot — 24
// hours is the operational figure this deployment picks, not a contract value.
const (
	DefaultResetGrantTTLMs int64 = 15 * 60_000
	DefaultSetupGrantTTLMs int64 = 24 * 60 * 60_000
)

// Grant redemption failures — each maps 1:1 onto a security-model/1 error code
// (SEC-035, Error taxonomy).
var (
	ErrGrantNotFound        = errors.New("auth: no grant matches this code")
	ErrGrantExpired         = errors.New("auth: grant expired")          // GRANT_EXPIRED
	ErrGrantAlreadyRedeemed = errors.New("auth: grant already redeemed") // GRANT_ALREADY_REDEEMED
	ErrGrantPurposeMismatch = errors.New("auth: grant purpose mismatch") // GRANT_PURPOSE_MISMATCH
	// ErrGrantAttemptBudget is the SEC-033 attempt budget being exhausted:
	// distinct from a wrong code, because the caller is now being refused
	// without the code even being checked.
	ErrGrantAttemptBudget = errors.New("auth: grant redemption attempt budget exhausted")
)

// MintGrantOptions parameterizes MintGrant. Purpose, ResultingPrincipalKind and
// TTLMs are required; the rest carry SEC-030's defaults.
type MintGrantOptions struct {
	Purpose                string
	ResultingPrincipalKind string
	ScopeNode              string
	Labels                 map[string]string
	Role                   Role
	TTLMs                  int64
	RedemptionMode         string
	MaxRedemptions         int
	ConsentRecord          string
	IssuedVia              string
	// Actor and TraceID name WHO minted this grant and under which api/1
	// Trace-Id, for the SEC-034 record MintGrant emits. Actor defaults to
	// UnresolvedActorPrincipal — an installer-run first-boot bootstrap genuinely
	// has no principal to attribute — and TraceID to a fresh id, exactly as any
	// other audit record with no inbound trace does.
	//
	// They are OPTIONS rather than positional arguments because the emission is
	// unconditional either way: SEC-034 is satisfied by MintGrant whether or not
	// a caller filled these in, so forgetting them costs attribution quality and
	// can never cost the record itself.
	Actor   string
	TraceID string
}

// MintedGrant is a freshly issued grant: the row plus the RAW code, which exists
// in plaintext exactly once (here) and is never recoverable from the store.
type MintedGrant struct {
	Grant GrantRow
	Code  string
}

// MintGrant creates a grant and returns its one-time code. The code carries 256
// bits of crypto/rand entropy — above SEC-032's 128-bit floor — and is persisted
// only as HashToken(code).
func (s *Store) MintGrant(ctx context.Context, opt MintGrantOptions) (MintedGrant, error) {
	if !ValidPurpose(opt.Purpose) {
		return MintedGrant{}, fmt.Errorf("auth: %q is not a grant purpose (SEC-030)", opt.Purpose)
	}
	if !ValidPrincipalKind(opt.ResultingPrincipalKind) {
		return MintedGrant{}, fmt.Errorf("auth: %q is not a principal kind (SEC-001)", opt.ResultingPrincipalKind)
	}
	if opt.TTLMs <= 0 {
		return MintedGrant{}, errors.New("auth: a grant needs a positive ttl (SEC-032)")
	}
	if opt.RedemptionMode == "" {
		opt.RedemptionMode = RedemptionOneTime // SEC-031: single-use by default
	}
	switch opt.RedemptionMode {
	case RedemptionOneTime:
		// SEC-031/036: a one-time grant's redemption count may never exceed one,
		// so the bound is fixed here rather than taken from the caller.
		opt.MaxRedemptions = 1
	case RedemptionMulti:
		if opt.MaxRedemptions < 1 {
			return MintedGrant{}, errors.New("auth: a multi grant must state its redemption bound (SEC-031)")
		}
	default:
		return MintedGrant{}, fmt.Errorf("auth: %q is not a redemption mode (SEC-031)", opt.RedemptionMode)
	}
	if opt.IssuedVia == "" {
		opt.IssuedVia = IssuedViaAPI
	}
	if opt.IssuedVia != IssuedViaAPI && opt.IssuedVia != IssuedViaConsole {
		return MintedGrant{}, fmt.Errorf("auth: %q is not an issuance channel (SEC-030)", opt.IssuedVia)
	}
	if opt.Role != "" && !ValidRole(opt.Role) {
		return MintedGrant{}, fmt.Errorf("auth: %q is not a role (SEC-010)", opt.Role)
	}
	code, err := MintGrantCode()
	if err != nil {
		return MintedGrant{}, err
	}
	id, err := s.mintID("grant")
	if err != nil {
		return MintedGrant{}, err
	}
	if opt.Labels == nil {
		opt.Labels = map[string]string{}
	}
	labelsJSON, err := json.Marshal(opt.Labels)
	if err != nil {
		return MintedGrant{}, fmt.Errorf("auth: encode grant labels: %w", err)
	}
	row := GrantRow{
		GrantID: id, Purpose: opt.Purpose, ResultingPrincipalKind: opt.ResultingPrincipalKind,
		ScopeNode: opt.ScopeNode, Labels: opt.Labels, Role: opt.Role, TTLMs: opt.TTLMs,
		RedemptionMode: opt.RedemptionMode, MaxRedemptions: opt.MaxRedemptions,
		ConsentRecord: opt.ConsentRecord, IssuedVia: opt.IssuedVia,
		IssuedAt: s.nowMs(), CodeHash: HashToken(code),
	}
	if err := s.writeTx(ctx, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx,
			`INSERT INTO grants (grant_id, purpose, resulting_principal_kind, scope_node, labels, role,
			                     ttl_ms, redemption_mode, max_redemptions, redemption_count,
			                     consent_record, issued_via, issued_at, code_hash)
			 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?)`,
			row.GrantID, row.Purpose, row.ResultingPrincipalKind, row.ScopeNode, string(labelsJSON),
			string(row.Role), row.TTLMs, row.RedemptionMode, row.MaxRedemptions,
			row.ConsentRecord, row.IssuedVia, row.IssuedAt, row.CodeHash)
		return err
	}); err != nil {
		return MintedGrant{}, fmt.Errorf("auth: mint grant: %w", err)
	}
	// SEC-034: "Every grant creation ... MUST emit an audit.event carrying that
	// grant's purpose and issued_via in its payload."
	//
	// It is emitted HERE, in the one function that creates a grant, rather than
	// in each issuing flow. That placement is the requirement's own word "every"
	// taken structurally: a flow added later cannot forget an emission it does
	// not perform, and the two fields SEC-034 names are read off the row that was
	// just persisted rather than off the caller's intent, so a flow that asked
	// for one purpose and stored another is recorded as what it stored.
	//
	// The raw code is NOT in this record and cannot be: the record names the
	// grant by grant_id, which is SEC-051's "the code or URL identifies a grant;
	// it is not itself a rendered credential" applied to the audit trail.
	s.auditor.Emit(Record{
		TraceID: opt.TraceID, Actor: auditActor(opt.Actor), Action: ActionGrantCreated,
		Target: "grant:" + row.GrantID, Result: events.AuditResultSuccess,
		Purpose: row.Purpose, IssuedVia: row.IssuedVia,
	})
	return MintedGrant{Grant: row, Code: code}, nil
}

// auditActor resolves an actor id for a record, falling back to the reserved
// "no principal resolved" id rather than emitting an empty actor EVT-080 would
// reject (and events.Validate would then drop, losing a mandatory emission).
func auditActor(actor string) string {
	if actor == "" {
		return UnresolvedActorPrincipal
	}
	return actor
}

// RedeemGrantOption carries the attribution RedeemGrant's own SEC-034 record
// needs. It is an option set rather than extra parameters because the redeeming
// principal is frequently not known until the consume function has run — the
// first-boot claim CREATES the principal inside its own transaction — so the
// actor has to be supplied as something read after commit, not before.
type RedeemGrantOption func(*redeemOptions)

type redeemOptions struct {
	actor   func() string
	traceID string
}

// RedeemedBy names the principal the redemption is attributed to. The value is
// resolved AFTER the transaction commits, so a caller whose principal is created
// inside consume can close over the variable it assigns there.
func RedeemedBy(actor func() string) RedeemGrantOption {
	return func(o *redeemOptions) { o.actor = actor }
}

// RedeemTraceID propagates the api/1 Trace-Id of the request performing the
// redemption onto its audit record.
func RedeemTraceID(traceID string) RedeemGrantOption {
	return func(o *redeemOptions) { o.traceID = traceID }
}

// InvalidateGrants deletes every unredeemed grant of a purpose — how a fresh
// `setup` grant invalidates whatever setup grant preceded it (SEC-065's
// regenerate semantics, and what keeps a box from accumulating live claim codes
// across restarts).
func (s *Store) InvalidateGrants(ctx context.Context, purpose string) error {
	return s.writeTx(ctx, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx, `DELETE FROM grants WHERE purpose = ?`, purpose)
		return err
	})
}

// RedeemGrant performs SEC-036's ATOMIC CHECK-AND-CONSUME: it resolves code,
// checks purpose and expiry, and increments the redemption count — all inside
// ONE transaction, with the increment additionally guarded by a compare-and-swap
// on the count it read (`WHERE redemption_count = ?`).
//
// SEC-036 is unusually explicit about what this must guarantee: "of two
// simultaneous requests presenting the same code, at most one MUST receive
// success and the other MUST receive GRANT_ALREADY_REDEEMED — a grant's
// redemption count MUST NOT ever exceed one regardless of concurrency." Two
// independent mechanisms enforce that here, and both are load-bearing rather
// than one being decoration:
//
//  1. The whole body runs in a single immediate transaction under the store's
//     write lock, so no second redemption interleaves between the read and the
//     write.
//  2. The UPDATE's WHERE clause names the exact count the SELECT observed, so
//     even if (1) were relaxed later — a second connection, a different driver,
//     a distributed store — a losing racer's UPDATE matches zero rows and is
//     reported as already-redeemed rather than silently succeeding.
//
// The caller MUST perform whatever the grant authorizes inside consume, which
// runs in the same transaction: a grant marked consumed whose effect then failed
// to commit would be a code burned for nothing.
func (s *Store) RedeemGrant(ctx context.Context, code, wantPurpose string, consume func(tx *sql.Tx, g GrantRow) error, opts ...RedeemGrantOption) (GrantRow, error) {
	var ro redeemOptions
	for _, opt := range opts {
		opt(&ro)
	}
	hash := HashToken(code)
	var out GrantRow
	err := s.writeTx(ctx, func(tx *sql.Tx) error {
		var (
			g          GrantRow
			labelsJSON string
			role       string
		)
		err := tx.QueryRowContext(ctx,
			`SELECT grant_id, purpose, resulting_principal_kind, scope_node, labels, role,
			        ttl_ms, redemption_mode, max_redemptions, redemption_count,
			        consent_record, issued_via, issued_at, code_hash
			 FROM grants WHERE code_hash = ?`, hash).
			Scan(&g.GrantID, &g.Purpose, &g.ResultingPrincipalKind, &g.ScopeNode, &labelsJSON, &role,
				&g.TTLMs, &g.RedemptionMode, &g.MaxRedemptions, &g.RedemptionCount,
				&g.ConsentRecord, &g.IssuedVia, &g.IssuedAt, &g.CodeHash)
		if errors.Is(err, sql.ErrNoRows) {
			return ErrGrantNotFound
		}
		if err != nil {
			return err
		}
		g.Role = Role(role)
		if labelsJSON != "" {
			_ = json.Unmarshal([]byte(labelsJSON), &g.Labels)
		}

		// SEC-035's three refusals, in the order that leaks least: a purpose
		// mismatch is decided before expiry, so a pairing code presented to the
		// credential-reset endpoint is refused as a mismatch whether or not it
		// has also aged out.
		if g.Purpose != wantPurpose {
			return ErrGrantPurposeMismatch
		}
		if g.RedemptionCount >= g.MaxRedemptions {
			return ErrGrantAlreadyRedeemed
		}
		if s.nowMs() >= g.ExpiresAt() {
			return ErrGrantExpired
		}

		// Consume FIRST, then run the caller's effect: if the effect fails, the
		// whole transaction (consumption included) rolls back.
		res, err := tx.ExecContext(ctx,
			`UPDATE grants SET redemption_count = redemption_count + 1
			 WHERE grant_id = ? AND redemption_count = ?`, g.GrantID, g.RedemptionCount)
		if err != nil {
			return err
		}
		n, err := res.RowsAffected()
		if err != nil {
			return err
		}
		if n != 1 {
			// The compare-and-swap lost: another redemption consumed this grant
			// between the SELECT and the UPDATE.
			return ErrGrantAlreadyRedeemed
		}
		g.RedemptionCount++
		if consume != nil {
			if err := consume(tx, g); err != nil {
				return err
			}
		}
		out = g
		return nil
	})
	if err != nil {
		return GrantRow{}, err
	}
	// SEC-034's other half: "every grant redemption MUST emit an audit.event
	// carrying that grant's purpose and issued_via", so "a recovery-purpose,
	// console-issued redemption is distinguishable in the audit trail from a
	// routine invite redemption months later". Both fields come off the REDEEMED
	// row, so `issued_via` records the channel the grant was ISSUED over — which
	// is the distinction the requirement's own sentence asks for — rather than
	// the channel the redemption arrived on.
	//
	// Emitted only on success, and after the transaction committed. A refused
	// redemption is not a grant redemption, and IS recorded separately by the
	// refusing surface — which is the only layer that knows the attempt's source
	// and must not put the presented code in a record (SEC-051). See
	// Handlers.RedeemCredentialReset, which records both the rate-limited and
	// the wrong-code refusal against the source address.
	actor := ""
	if ro.actor != nil {
		actor = ro.actor()
	}
	s.auditor.Emit(Record{
		TraceID: ro.traceID, Actor: auditActor(actor), Action: ActionGrantRedeemed,
		Target: "grant:" + out.GrantID, Result: events.AuditResultSuccess,
		Purpose: out.Purpose, IssuedVia: out.IssuedVia,
	})
	return out, nil
}

// GrantAttemptBudget bounds repeated guesses at a live grant's code (SEC-033):
// "a grant-issuing endpoint MUST enforce a redemption rate limit and an attempt
// budget against repeated guesses of a live grant's code — the enforced control;
// a limit on issuance alone is not a substitute, since guessing a code that
// already exists is the attack this bounds, not minting new ones."
//
// It is reenroll.RateLimiter, reused verbatim rather than reimplemented: that
// type is already a per-key counting window driven by an injected clock, which
// is exactly the shape this needs.
//
// The key is `(purpose, SOURCE ALLOCATION)` — RequestSource's own reduction of
// the request's source: the address for IPv4, its /64 for IPv6, since a single
// IPv6 host mints addresses within its own /64 for free and a budget keyed on
// something free to mint bounds nothing.
//
// Keying on the source rather than on its class is load-bearing.
// `IPClass` has three values, so keying on it puts every host
// on the LAN into ONE bucket: ten guesses per window from any single machine —
// drivable cross-origin from a victim's own browser, since the redeem route
// takes a simple POST — would exhaust the bucket and deny credential reset to
// everyone else in that class until it drained. On an appliance whose only
// other recovery path is a root-only console socket, that is account recovery
// taken out by an unauthenticated caller who never has to guess correctly.
//
// A per-address bucket is not a complete answer either — an attacker with many
// source addresses gets a bucket each — but the two failure modes are not
// comparable: per-address, a guesser buys attempts only against themselves,
// while per-class they buy a denial against everybody. The address is what the
// platform can attribute an attempt to, so it is what the budget is spent from.
type GrantAttemptBudget struct {
	limiter *reenroll.RateLimiter
}

// Grant attempt-budget defaults: 10 redemption attempts per source ADDRESS per
// purpose per 15 minutes. Against a 256-bit code that is astronomically more
// than an attacker needs to be hopeless, and far more than a human fumbling a
// hand-typed setup code needs.
const (
	DefaultGrantAttemptLimit          = 10
	DefaultGrantAttemptWindowMs int64 = 15 * 60_000
)

// NewGrantAttemptBudget returns a budget permitting limit redemption attempts
// per (purpose, source address) within any windowMs-long window.
func NewGrantAttemptBudget(limit int, windowMs int64) *GrantAttemptBudget {
	return &GrantAttemptBudget{limiter: reenroll.NewRateLimiter(limit, windowMs)}
}

// NewDefaultGrantAttemptBudget returns a budget on the defaults above.
func NewDefaultGrantAttemptBudget() *GrantAttemptBudget {
	return NewGrantAttemptBudget(DefaultGrantAttemptLimit, DefaultGrantAttemptWindowMs)
}

// Allow records one redemption attempt from source and reports whether it may
// proceed. A false return MUST refuse the request WITHOUT looking the code up —
// the budget exists to stop the lookups, not to filter their results.
//
// source is the attempt's source address (RequestSource): the host the attempt
// is attributable to, so one host exhausting its budget spends only its own.
func (b *GrantAttemptBudget) Allow(purpose, source string, nowMs int64) bool {
	return b.limiter.Allow(purpose+"|"+source, nowMs)
}
